調整a uninstall指令

diff --git a/bin/a-uninstall b/bin/a-uninstall
--- a/bin/a-uninstall
+++ b/bin/a-uninstall
@@ -6,21 +6,36 @@ function main() {
     exit 0
   fi
 
-  IFS=$'\n'
+  printf "開始卸載 %s\n\n" "$1"
 
+  IFS=$'\n'
   red=$(tput setaf 1)
   normal=$(tput sgr0)
+  app_path="$1"
 
-  echo $1
-
-  if [ ! -e "$1/Contents/Info.plist" ]; then
-    printf "%s\n" "Cannot find app plist"
-    exit 1
+  if [[ "$app_path" != "/Applications/"* ]]; then
+    app_path="/Applications/"$app_path
+  fi
+  if [[ "$app_path" != *".app" ]]; then
+    app_path=$app_path".app"
   fi
 
-  bundle_identifier=$(/usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "$1/Contents/Info.plist" 2> /dev/null)
+  only_clean_app_data="false"
 
-  if [ "$bundle_identifier" = "" ]; then
+  if [ ! -e "$app_path/Contents/Info.plist" ]; then
+    printf "%s\n" "Cannot find app plist"
+    
+    printf "only clean app data (y or n)? "
+    read -r answer
+    if [ "$answer" = "y" ]; then
+      only_clean_app_data="true"
+    else
+      exit 1
+    fi
+  fi
+
+  bundle_identifier=$(/usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "$app_path/Contents/Info.plist" 2> /dev/null)
+  if [ "$bundle_identifier" = "" ] && [ "$only_clean_app_data" = "false" ]; then
     printf "%s\n" "Cannot find app bundle identifier"
     exit 1
   fi
@@ -28,10 +43,9 @@ function main() {
   printf "%s\n" "Checking for running processes…"
   sleep 1
 
-  app_name=$(basename $1 .app)
+  app_name=$(basename $app_path .app)
 
-  processes=($(pgrep -afil "$app_name" | grep -v "uninstall-cli.sh"))
-
+  processes=($(pgrep -afil "$app_name" | grep -v  $(basename "$0"))) | grep -v "a.py uninstall"
   if [ ${#processes[@]} -gt 0 ]; then
     printf "%s\n" "${processes[@]}"
     printf "$red%s$normal" "Kill running processes (y or n)? "
@@ -40,7 +54,7 @@ function main() {
       printf "%s\n" "Killing running processes…"
       sleep 1
       for process in "${processes[@]}"; do
-        echo $process | awk '{print $1}' | xargs sudo kill 2>&1 | grep -v "No such process"
+        echo $process | awk '{print $app_path}' | xargs sudo kill 2>&1 | grep -v "No such process"
       done
     fi
   fi
@@ -100,7 +114,10 @@ function main() {
     $(getconf DARWIN_USER_TEMP_DIR | sed "s/\/$//")
   )
 
-  paths=($1)
+  paths=($app_path)
+  if [ "$only_clean_app_data" = "true" ]; then
+    paths=()
+  fi
 
   for location in "${locations[@]}"; do
     paths+=($(find "$location" -iname "*$app_name*" -maxdepth 1 -prune 2>&1 | grep -v "No such file or directory" | grep -v "Operation not permitted" | grep -v "Permission denied"))
@@ -112,16 +129,26 @@ function main() {
 
   paths=($(printf "%s\n" "${paths[@]}" | sort -u));
 
-  printf "%s\n" "${paths[@]}"
+  if [ ${#paths[@]} -eq 0 ]; then
+    echo "unable to find app data"
+  else
+    printf "%s\n" "${paths[@]}"
+    printf "$red%s$normal" "Move app data to trash (y or n)? "
+    read -r answer
+    if [ "$answer" = "y" ]; then
+      printf "%s\n" "Moving app data to trash…"
+      sleep 1
+      posixFiles=$(printf ", POSIX file \"%s\"" "${paths[@]}" | awk '{print substr($0,3)}')
+      osascript -e "tell application \"Finder\" to delete { $posixFiles }" > /dev/null
+      printf "%s\n" "Done"
+    fi
+  fi
 
-  printf "$red%s$normal" "Move app data to trash (y or n)? "
+  printf "need homebrew uninstall (y or n)? "
   read -r answer
   if [ "$answer" = "y" ]; then
-    printf "%s\n" "Moving app data to trash…"
-    sleep 1
-    posixFiles=$(printf ", POSIX file \"%s\"" "${paths[@]}" | awk '{print substr($0,3)}')
-    osascript -e "tell application \"Finder\" to delete { $posixFiles }" > /dev/null
-    printf "%s\n" "Done"
+    printf "homebrew uninstalling $app_name..."
+    brew uninstall "$app_name"
   fi
 }
 
